#!/usr/bin/env bash

if [ ! -d "$HOME/.dotfiles" ];
then
  echo "Couldn't locate ~./dotfiles"
  exit
fi

cd $HOME/.dotfiles

# syncing with remote repo
echo "--- Syncing repository ---------------------------"
git pull
git add .
git commit -m "update"
git push

# syncing all
echo "--- Performing stow sync -------------------------"
stow --verbose=3 --target="$HOME" .

echo "--- Complete! ------------------------------------"
exit
