#!/usr/bin/env bash

if [ ! -d "$HOME/.dotfiles" ];
then
  echo "Couldn't locate ~./dotfiles"
  exit
fi

cd $HOME/.dotfiles

# syncing with remote repo
git pull
git add .
git commit -m "update"
git push

# syncing all
stow --verbose=2 --target="$HOME" .

echo "sync complete"
