theme = "my_fleet_dark"

[editor]
mouse = true
cursorline = true
auto-save = true

[editor.statusline]
left = ["mode", "separator", "spinner", "file-modification-indicator"]
center = ["file-name", "read-only-indicator", "file-encoding"]
right = ["diagnostics", "selections", "register", "separator", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true


